--enable-features=UseOzonePlatform,WaylandWindowDecorations,AllowQt,VaapiVideoDecoder,VaapiIgnoreDriverChecks
--ozone-platform=wayland
--password-store=gnome-libsecret
--gtk-version=4
--enable-unsafe-webgpu
